version: '3'

services:    
    app:
        build: app/.
        labels:
            project: "login_register"
            day: "21 Apr 2020"
        #restart: unless-stopped
        ports:
            - "80:80"
        links:
            - db
        depends_on:
            - db
    db:
        image: mysql:latest
        labels:
            project: "login_register"
            day: "21 Apr 2020"        
        #restart: unless-stopped
        ports:
           - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: laukik
            MYSQL_DATABASE: userdb