version: '3'

services:    
    app:
        container_name: app
        build: 'app/.'
        restart: unless-stopped
        links:
            - mysql
        depends_on:
            - mysql
        ports:
            - "5000:5000"
    mysql:
        container_name: mysql
        build: 'mysql/.'
        restart: unless-stopped
        #volumes:
        #    - mysql-data:/var/lib/mysql
        restart: unless-stopped
        ports:
           - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        container_name: phpmyadmin
        build: 'phpmyadmin/.'
        restart: unless-stopped
        links:
            - mysql
        depends_on:
            - mysql
        ports:
            - "80:80"  
            

#volumes:
#    mysql-data:
#        driver: local