version: '3'

services:    
    app:
        build: app/.
        ports:
            - "80:80"
        links:
            - db
        depends_on:
            - db
    db:    
        build: db/.
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: supersecure