version: '3'

services:    
    app:
        build: app/.
        ports:
            - "80:80"
        links:
            - db
        depends_on:
            - db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example