version:'3'

services: 
    db :
        image: mysql:latest
        ports:
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: root   
    app:
        build: ./app
        links:
            - db
        ports:
            - "5000:5000"