version: '3'

services:    
    app:
        container_name: login_register_app
        build: app/.
        labels:
            project: "login_register"
            day: "21 Apr 2020"
        restart: unless-stopped
        links:
            - db
        depends_on:
            - db
        ports:
            - "80:80"
    db:
        container_name: login_register_db
        image: mysql:latest
        volumes:
            - mysql-data:/var/lib/mysql
        labels:
            project: "login_register"
            day: "21 Apr 2020" 
        command: --default-authentication-plugin=mysql_native_password       
        restart: unless-stopped
        ports:
           - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: LBR123
            MYSQL_DATABASE: userdb
            MYSQL_USER: laukikrupne
            MYSQL_PASSWORD: LBR123
volumes:
  # just a persistance data
    mysql-data:
        driver: local